const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2348165846414",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK05TT0lzYmtkSUFKdkQ4TlhxUkNtNEpFaHcwV0RsbkdtbzUxVDZxZ3EwMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieHpxUmQvMzZVWVJ4S3FwQW9uN2JOWHlCSko0Wk9FZTBLbHJFRjNQQW1FND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5R2taOXVlMUJjVkkxYmpFS3Jzc25lVkZDN29FcDdmdGlydXNCVG1iSFZVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJNcHpvV20yUTREcjNQcmM5SWZ3Z2JFelBuZ2dGNnlXdmZWY2JWT2VkSGpBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtCK1RFN2xOWEMrV21TU0w5TERiTi90OHRDZ0ZsZUdmVkU1M3VWcnVlRmM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InQ4NVA1OSs2bXdWMVN4Q2cyWWg3bE9KcU95aEIxMWJKS1ZHZkRTOGdxeXM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUt1dWFONS9TQzVQR0g2dWpxSnlXWGNDL2RlYkZtSThuVjc1c0RLYW5YND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVHMvOVRLV1M1aU1jalM1NkN2eVd4d3VFeU84REQ3MUNQTTMvU2NwYkVVbz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Imp4bHAzaEMwQ3VmQXByQzZVck0wWnhsemxWVTNYMEdkaWJQdnQrVm5TOHlPMVNzcGJrdnNEMGFLa3FiSndLN0hrQWNsaXZxTWJUVWF0QW5Db1NLMUJRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NCwiYWR2U2VjcmV0S2V5IjoiSDdKYUhNaHZwM3c4bWFaSllWZmt6YzN4b3ZPN1RTRkVyUmdTMVlSaUFWVT0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOltdLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiWFpDSkxYTFAiLCJtZSI6eyJpZCI6IjIzNDkxMzA1Mzk0ODI6MzJAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiSGltIiwibGlkIjoiNTc0OTI4ODUyMjk2NjA6MzJAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKV2IycmtCRVBLazFMd0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ6RzMzaGNJMnl5Q0lheHc2WUd6N2NGMHpwY1NRZW5vNGFVem9lcElMWmhNPSIsImFjY291bnRTaWduYXR1cmUiOiJFMnA3aDJtNTYvZFpUcEdzc3MxRVZaNWJVVGZ3QlZQSHN0dVR0aEw1cnFsNWJSa2JkMjRKUFpycFRJTmxoY2hzRVdLa0ZaYVBvZmZhdlZsNEQxMjRDQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiQm5GRUw2TmtnTDF4UytYQ0REU2doV1UrNmtEeFRzUlhhMzQ1TWIvM2JLYWxxNDl1L3dmQTdDL3l0M01TN0lReTlCUXdHZ1pCT2I0aG9PQnF5NVJQQlE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ5MTMwNTM5NDgyOjMyQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmN4dDk0WENOc3NnaUdzY09tQnMrM0JkTTZYRWtIcDZPR2xNNkhxU0MyWVQifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBZ0lFZz09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNzgyMjg0NywibGFzdFByb3BIYXNoIjoiMkc0QW11IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFQWXcifQ==",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
